---

# Sample config file for koha-plugin-starter

# Name of the plugin
name: My plugin

# A short description of the plugin
description: My wonderful Koha plugin

# Some info about the author
author_name: My Name
author_email: me@example.org

# Format of the README file, "pod" or "md"
readme_format: md

# Namespace
# "Koha::Plugin::" will be prepended to the part of the namespace you enter here.
# It is customary to use some domain name associated with your organisation of
# person as part of the namespace. For example, if your employer uses the
# example.org and you are creating a plugin related to "foo", the namespace you
# enter here might be "Org::Example::Foo"
namespace: "Org::Example::Foo"

## Capabilities

# Now we configure what our plugin should be able to do. There will be one key
# per possible capablity. The value of these keys should be 1 to enable the
# capability and 0 to not enable it.

# Report plugin
report: 1

# Tool plugin
tool: 0

# "To MARC" plugin
to_marc: 0

# OPAC online payment plugin
opac_online_payment: 0

# Configure
configure: 0

# Install and uninstall
install: 1

# Database tables that should be created in the install subroutine and 
# destroyed in the uninstall subroutine
tables:
  - table1
  - table2

## Development mode

# If set to 0, the script will check if the README already exists, and exit
# if it does. This ensures you do not overwrite your work if you run the script
# against some directory too many times.
#
# If set to 1, the files generated by the plugin starter will be overwritten
# if yu run the script against a directory where it has already created files.
# This is useful when doing testing and development of the plugin starter itself.
devel_mode: 0
